#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' && github.sha || '' }}
  cancel-in-progress: true

jobs:
  duckdb-next-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    if: false   # extension-template is currently not compatible with main
    with:
      duckdb_version: main
      ci_tools_version: main
      extension_name: markdown

  duckdb-stable-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.3.1
    with:
      duckdb_version: v1.3.1
      ci_tools_version: v1.3.1
      extension_name: markdown
      # Pin to vcpkg commit with verified cmark-gfm support (tested 2025-01-08)
      vcpkg_commit: bffcbb75f71553824aa948a7e7b4f798662a6fa7
      vcpkg_url: https://github.com/Microsoft/vcpkg.git
      # exclude_archs: 'windows_amd64;windows_amd64_mingw'

#  code-quality-check:
#    name: Code Quality Check
#    uses: duckdb/extension-ci-tools/.github/workflows/_extension_code_quality.yml@main
#    with:
#      duckdb_version: v1.3.1
#      ci_tools_version: main
#      extension_name: markdown
#      format_checks: 'format;tidy'
